version: "3.7"

networks:
  postgresql-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"

services:
  database_acar:
    image: postgres
    container_name: database_acar
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dockeruser
      - POSTGRES_PASSWORD=dockerpass
      - POSTGRES_DB=acar
      - PGPASSWORD=dockerpass
    volumes:
      - pgdata:/data/postgres
    networks:
      - postgresql-network
    healthcheck:
      test: ["CMD", "psql", "-U", "dockeruser", "-h", "database_acar", "-d", "acar", "-c", "SELECT 1;", "-q"]
      interval: 1m
      timeout: 10s
      retries: 5

  app:
    build: .
    container_name: app_acar
    restart: always
    ports:
      - 4444:4444
    volumes:
      - .:/usr/app
    networks:
      - postgresql-network
    links:
      - database_acar
    depends_on:
      - database_acar
    healthcheck:
      test: wget --quiet --tries=1 --spider http://localhost:4444/healthcheck || exit 1
      interval: 2s
      timeout: 1s
      retries: 3
      start_period: 20s

volumes:
  pgdata:
    driver: local